### ISSUE TITLE
Fluid transfer stopping

### ISSUE THREAD

**Issue by Caopr** [CyclopsMC/FluidConverters#36] opened 2017-06-18 17:43 UTC
Was a bit finicky to get started eventually it started going through. But whenever the output tanks fill then later become empty it wont work again until I remove the input pipes then place them down again. Even if I remove the fluid block itself and place it back. I have Mekanism pipes set up in it but when it stopped I tried Actually additions fluid laser relays with no effect Same with Extra utilities fluid transfer nodes. the only way to get it working again is by re-placing mekanism pipes 

Below are pictures of my setup.

![2017-06-18_13 35 52](https://user-images.githubusercontent.com/29389055/27262749-77d9ea92-542b-11e7-84bb-63ed8135526c.png)
![2017-06-18_13 39 03](https://user-images.githubusercontent.com/29389055/27262757-8fa02efc-542b-11e7-88f2-c05fa65e9b32.png)
![2017-06-18_13 40 08](https://user-images.githubusercontent.com/29389055/27262762-a983fcfe-542b-11e7-9096-7c67ff4e3558.png)
![2017-06-18_13 40 27](https://user-images.githubusercontent.com/29389055/27262765-b5b762ae-542b-11e7-95c4-5764e4e13d91.png)

When this happens the buffer usually has around 80/1000 in it. So it might be freezing or getting stuck if the flow stops. otherwise if it continually flows its fine

![2017-06-18_13 42 13](https://user-images.githubusercontent.com/29389055/27262778-fea2747c-542b-11e7-86ff-b7585dcbc297.png)

**Comment by rubensworks** [comment] 2017-06-18 17:50
Does the chunk unload by any chance?

1.11?

**Comment by Caopr** [comment] 2017-06-18 17:53
I havent gone elsewhere for it to unload. and yes 1.11.2 same as before :3

**Comment by rubensworks** [comment] 2017-06-21 15:31
I wasn't able to reproduce this, except for when I also made the input of the converter and output.
So in your case, I assume the right side of the converter also outputs blood.
This can cause the input fluid to be ejected to the same side immediately, which makes it seem like it's frozen.
If this is indeed the case, please let me know, so I can close this issue.

I've added a restriction so that you won't be able to input fluids to outputs anymore, so this should make this a bit more user-friendly.

**Comment by Fundryi** [comment] 2017-06-23 14:03
Hi, I saw the issue and it looks similar to mine. Could be just a wrong config but still. Maybe I get help here.

My config: https://gist.github.com/NoplixDE/3b201d6f20ffce31a9374fb0a45ca416
But doesn't work. See: https://i.imgur.com/clO4qya.gifv
The essence is stuck (it doesn't produce more) only that tiny little as you can see.

**Comment by rubensworks** [comment] 2017-06-23 17:44
@NoplixDE Are you using the latest version? Did you read my previous comment?

**Comment by Fundryi** [comment] 2017-06-23 17:48
yes newest version on 1.10 & yes I read it but i don't get smarter out of it.

**Comment by rubensworks** [comment] 2017-06-23 17:52
@NoplixDE The side that you are inputting, did you configure a fluid to that side by right-clicking on it with a fluid item? If so, remove it, and see if it works then.

**Comment by Fundryi** [comment] 2017-06-23 18:15
No still doesn't work,
Maybe its because of my edit of

machine {
    # The amount of mB per tick that can be converted.
    I:fluidconverter.mBRate=1000
}

**Comment by rubensworks** [comment] 2017-06-23 18:19
@NoplixDE It looks like there is fluid going through that fluiduct to the right, no?
Or did the original rate seem to be higher?

What happens if you reconnect the input pipe?

**Comment by Fundryi** [comment] 2017-06-23 18:24
No it only does for one sec but it stops instant and, doesn't fill up any tanks. And I nearly tried everything with the pipes.

**Comment by rubensworks** [comment] 2017-06-23 18:27
Ah, I didn't read your earlier comment propertly:
> The essence is stuck (it doesn't produce more) **only that tiny little as you can see**.

So it does produce, just slow(er).
This means that your change to the `mBRate` doesn't get applied apparently, I'll have to look into that.

**Comment by Fundryi** [comment] 2017-06-23 18:29
Whats the default again im gonna try it with that.

**Comment by rubensworks** [comment] 2017-06-23 18:34
@NoplixDE The default is even lower: `100`.

**Comment by Fundryi** [comment] 2017-06-23 18:35
Whats the default xD

**Comment by Caopr** [comment] 2017-06-24 04:25
Only 1 side was set to output and that was the life essence side I pictured. All other were blank

**Comment by rubensworks** [comment] 2017-06-25 06:34
Ok, with an mbRate of 1000 I managed to reproduce (and fix) the issue.

There was a hardcoded part in the algorithm that assumed an mbRate of 100 at all times, which caused issues if this was not the case.
Will publish new releases now.

**Comment by Fundryi** [comment] 2017-06-25 07:14
Yayy! thank you so much!

**Comment by Caopr** [comment] 2017-06-26 18:07
Gah still happening for me Dx. Gets stuck with the internal buffer at 40.

**Comment by rubensworks** [comment] 2017-06-26 18:08
@Caopr What fluid converter config and mbRate are you using?

**Comment by Caopr** [comment] 2017-06-26 18:14
The pipe has an internal buffer of 1000mb and a pumping rate of 100mb Its the pipe from mekanism as pictured above. it onyl flows again once I reset a mekanism type pipe nothing else.

**Comment by Caopr** [comment] 2017-06-26 18:15
{
  "groupId": "blood",
  "groupName": "Blood to Life",
  "fluidElements": [
    {
      "fluidName": "evilcraftblood",
      "value": 1.0
    },
    {
      "fluidName": "lifeessence",
      "value": 2.0
    }
  ],
  "lossRatio": 0,
  "hasRecipe": true,
  "hasDefaultRecipe": true
}

**Comment by rubensworks** [comment] 2017-06-26 18:16
@Caopr But what is the configured mbRate in the FC config file?

**Comment by Caopr** [comment] 2017-06-26 18:17
machine {
    # The amount of mB per tick that can be converted.
    I:fluidconverter.mBRate=100
}
 didint change anything in that one

**Comment by rubensworks** [comment] 2017-06-26 18:24
Hmm, then it must have something to do with with the external pumping rate of 100 somehow conflicting with the internal rate. Will have to look into it.

**Comment by Caopr** [comment] 2017-06-26 18:40
Testing if its purely the mekanism piping breaking it. made a new fluid converter and am only using extra utilities Fluid transfer node for the input. If that wont work ill try another. Ill see how it goes

**Comment by Caopr** [comment] 2017-06-26 18:41
Ok rip fluid transfer node. same thing. once it stopped for a second [as tanks filled] it refuses to start back up

**Comment by Caopr** [comment] 2017-06-26 18:43
And laser relays from actually additions just do nothing at all im out of ideas sorry

**Comment by rubensworks** [comment] 2017-06-26 18:45
@Caopr So nothing works at all? That seems strange.
Can you share another picture of your latest setup including the configured fluid input/output sides?

**Comment by Caopr** [comment] 2017-06-26 18:48
Its the exact same basically. re-tried all the above piping with a fresh fluid converter block each time. 1 output for life essence flowing to tank on the left. blood on right is supplied from Evilcraft blood farm. Tanks on left flow into blood altar [is a tank below blood altar acting as a buffer]

**Comment by rubensworks** [comment] 2017-06-26 18:52
Ok, something must be going horribly wrong then.
I'll try reproducing it soon.

Another question:
What happens if you pipe everything in an EvilCraft dark tank that is on top of the converter and that tank auto-exports to the bottom?

**Comment by Caopr** [comment] 2017-06-26 19:01
SEems to be working...perfectly fine :o with the dark tank auto importing directly

![2017-06-26_15 02 02](https://user-images.githubusercontent.com/29389055/27555645-73e1e966-5a80-11e7-8458-9441a239b2e1.png)

**Comment by rubensworks** [comment] 2017-06-26 19:02
So something must be going wrong with those pipes. Will check soon.

**Comment by Caopr** [comment] 2017-06-26 19:03
Might be a difference in how the fluid transfer is handled in evilcrafts tank compared to all the other mods

**Comment by rubensworks** [comment] 2017-06-26 19:04
Everything should just be using fluid capabilities, nothing much can go wrong there.

**Comment by Caopr** [comment] 2017-06-26 19:12
Well I know Mekanism pipes have a set limit of 100 mb per transfer. as does extra utilities fluid transfer nodes. I dont know the dark tanks transfer rate. or if it has a minimum like the others. if the number freaks out with 40 in the buffer the dark tank might just be able to ignore it and fill it fully

**Closed as completed** 2017-07-11 11:25 UTC
Labels: bug
