### ISSUE TITLE
crashed in client

### ISSUE THREAD

**Issue by scalda** [CyclopsMC/FluidConverters#5] opened 2014-09-03 21:21 UTC
I have just got round to adding this to my client and it has crashed, it works fine on the server now.

Here is the crash log https://dl.dropboxusercontent.com/u/8871364/crash%20log/crash-2014-09-03_21.34.21-client.txt

Hope it helps

Scalda

**Comment by rubensworks** [comment] 2014-09-04 11:36
Thanks for the report.
Commit 8f4796fe117171daec67d12c656bf92d5152018f should solve this issue. Could you try the latest build that can be found here?: https://drone.io/github.com/rubensworks/FluidConverters/files
Since I can't seem to reproduce this problem locally. Only the client mod file should be updated.

**Comment by scalda** [comment] 2014-09-04 16:44
i have tried that version it works fine if it is on its own but short of adding 100+ mods to see what is causing it to crash out i don't no

**Comment by rubensworks** [comment] 2014-09-04 18:42
Not sure what you mean with this, were you also able to test it with those mods that you used when the crash occurred? If so, I can close this issue and publish a new release.

**Comment by scalda** [comment] 2014-09-04 18:49
No I haven't been able to run it with the mods I have got loaded but it
does run when it's the only mod that is being loaded. Also when I ran it on
its own and I opened a single player world there was no tab or item to be
able to use your mod

**Comment by rubensworks** [comment] 2014-09-04 18:53
It's perfectly normal that you don't see a new tab if you haven't configured any fluid converter blocks in json configs as explained on the wiki, the creative tab is hidden in that case, since there are not blocks anyways.
As for the 100+ mods issue, does this dev build cause the same issue as the release build you had before?

**Comment by scalda** [comment] 2014-09-04 18:57
Ok fair enough on the tab.

And yes it is the same error with the Dev build as it was with the release
version

**Comment by rubensworks** [comment] 2014-09-04 18:58
Ok, could you send me an updated crash log? Since the error is impossible to occur at the same location, so it should happen somewhere else.

**Comment by scalda** [comment] 2014-09-04 19:04
Here is the latest report i have for that crash 

https://dl.dropboxusercontent.com/u/8871364/crash%20log/crash-2014-09-04_17.50.12-client.txt

I am at the moment add the mods i have got to fluid convertors 1 by 1 to see where the conflict is

**Comment by rubensworks** [comment] 2014-09-04 19:07
Ok thanks.
Dev build 10 should pop up soon here: https://drone.io/github.com/rubensworks/FluidConverters/files
Could you retry it with that one? This this it should work.

**Comment by scalda** [comment] 2014-09-04 19:08
Ok i will wait for it to finish building and i will test and let you know.

**Comment by scalda** [comment] 2014-09-04 19:18
That build has worked great, what ever it was you fixed work. now time for me to go through the wiki and add my own group

**Comment by rubensworks** [comment] 2014-09-04 19:20
Ok, that's great to hear!
Will publish a new release tomorrow containing this fix.

**Closed as completed by rubensworks** 2014-09-04 19:20 UTC

**Comment by scalda** [comment] 2014-09-04 19:21
Great I'll play with the Dev build til then.
